name: Check formatting

on:
  pull_request:
    branches: [ main ]
    paths:
      - "internal/**"

jobs:
  test:
    name: Check format
    runs-on: ubuntu-latest
    env:
      GO_VERSION: '1.25.5'

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Golang
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install gofumpt
        run: go install mvdan.cc/gofumpt@v0.9.2

      - name: Run gofumpt (cmd)
        run: |
          if [ -n "$(gofumpt -l ./cmd)" ]; then
            echo "Go files not properly formatted."
            echo "Rune 'gofumpt -w ./cmd' to fix."
            exit 1
          fi

      - name: Run gofumpt (internal)
        run: |
          if [ -n "$(gofumpt -l ./internal)" ]; then
            echo "Go files not properly formatted."
            echo "Rune 'gofumpt -w ./internal' to fix."
            exit 1
          fi
